export { default as LogoIcon } from './logo.svg';
export { default as BurguerMenu } from './burger-menu.svg';
export { default as ArrowDown } from './arrow-down.svg';
export { default as ArrowLeft } from './arrow-left.svg';
export { default as CheckMark } from './check-mark.svg';
export { default as Plus } from './plus.svg';
export { default as Close } from './close-circle.svg';
export { default as Pin } from './pin.svg';
export { default as Calendar } from './video-add.svg';
